version: '3.9'

services:
    swoole:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - COMPOSER_ALLOW_SUPERUSER=true
            - XDEBUG_CONFIG=client_host=host.docker.internal start_with_request=trigger
            - XDEBUG_MODE=debug
            - XDEBUG_SESSION=PHPSTORM
            - PHP_IDE_CONFIG=serverName=swoole
        ports:
            -   "9501:9501"
        volumes:
            -   ./:/app
        working_dir: /app
        command: php src/public/index.php

    swoole-ws:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - COMPOSER_ALLOW_SUPERUSER=true
            - XDEBUG_CONFIG=client_host=host.docker.internal start_with_request=trigger
            - XDEBUG_MODE=debug
            - XDEBUG_SESSION=PHPSTORM
            - PHP_IDE_CONFIG=serverName=swoole
        ports:
            -   "9511:9511"
        volumes:
            -   ./:/app
        working_dir: /app
        command: php src/public/ws.php